apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: pitin-service
  name: pitin-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: pitin-service-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: ${CERTIFICATE_ARN}
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10
spec:
  ingressClassName: alb
  rules:
    - host: service.pitin-ev.com
      http:
        paths:
          - path: /bsms
            pathType: Prefix
            backend:
              service:
                name: bsms-backend-svc
                port:
                  number: 80
          - path: /bsms-dev
            pathType: Prefix
            backend:
              service:
                name: bsms-dev-backend-svc
                port:
                  number: 80
