apiVersion: v1
kind: Service
metadata:
  namespace: pitin-service
  name: bsms-dev-backend-svc
spec:
  type: NodePort
  selector:
    app: bsms-dev-backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
